server:
  error:
    include-stacktrace: on_param


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/anime?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    username: root
    password: 20030927

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



